[general]
downloads_dir=/opt/airflow/dags/upload/downloads
selected_url=purplebook, dailymed, orangebook
# Number of months of DailyMed data to download
dailymed_months=1

[urls]
dailymed=https://dailymed.nlm.nih.gov/dailymed/spl-resources-all-drug-labels.cfm
orangebook=https://www.fda.gov/media/76860/download?attachment
purplebook=https://purplebooksearch.fda.gov/files/2023/purplebook-search-january-data-download.csv

[dest_directory]
dailymed=/opt/airflow/dags/jsonify/input/xml_files
orangebook=/opt/airflow/dags/jsonify/input/txt_files
purplebook=/opt/airflow/dags/jsonify/input/csv_files

[source_paths]
dailymed=prescription
orangebook=orangebook
purplebook=.

[file_patterns]
dailymed=*.xml
orangebook=products.txt
purplebook=*.csv
